import { cn } from "@/lib/utils";
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Providers from "@/components/Providers"
import { ModalProvider } from "@/components/modal-provider";
import { ToasterProvider } from "@/components/toaster-provider";


const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'wAIsely',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "antialiased min-h-screen ")}>
        <Providers>
            <ModalProvider/>
            <ToasterProvider/>
            {children}
        </Providers>
      </body>
    </html>
  );
}