import { cn } from "@/lib/utils";
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Providers from "@/components/Providers"
import Navbar from "@/components/Navbar";
import Link from "next/link"
import { LandingNavbar } from "@/components/landing-navbar";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'wAIsely',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "antialiased min-h-screen ")}>
        <Providers>
            {children}
        </Providers>
      </body>
    </html>
  );
}